import {
   LogoAstro,
   LogoBootstrap,
   LogoReact,
   LogoHTML,
   LogoCSS,
   LogoGit,
   LogoSass,
   LogoJS,
   LogoGsap,
   LogoFireBase,
} from "./assets/Icons";

export const projectsArray = [
   {
      id: 1,
      name: "Astro E-Commerce",
      src: "https://streamable.com/e/1hvr42?autoplay=1&nocontrols=1",
      github: "https://github.com/Valenmetal/React-Astro-E-Commerce",
      url: "https://valenmetal.github.io/React-Astro-E-Commerce/",
      logos: [
         <LogoReact />,
         <LogoAstro />,
         <LogoGsap />,
         <LogoSass />,
         <LogoGit />,
         <LogoHTML />,
         <LogoCSS />,
         <LogoJS />,
      ],
   },
   {
      id: 2,
      name: "Shoes E-Commerce 2.0",
      src: "https://streamable.com/e/hxrail?autoplay=1&nocontrols=1",
      github: "https://github.com/Valenmetal/React-Ecommerce",
      url: "https://valenmetal.github.io/React-Ecommerce/",
      logos: [
         <LogoReact />,
         <LogoFireBase />,
         <LogoSass />,
         <LogoBootstrap />,
         <LogoGit />,
         <LogoHTML />,
         <LogoCSS />,
         <LogoJS />,
      ],
   },
   {
      id: 3,
      name: "Shoes E-Commerce",
      src: "https://streamable.com/e/k97y58?autoplay=1&nocontrols=1",
      github: "https://github.com/Valenmetal/valenmetal.github.io",
      url: "https://valenmetal.github.io/",
      logos: [
         <LogoHTML />,
         <LogoCSS />,
         <LogoJS />,
         <LogoSass />,
         <LogoBootstrap />,
         <LogoGit />,
      ],
   },
];
